# Build stage
FROM node:14 AS build

RUN mkdir -p /home/client

WORKDIR /home/client

COPY . /home/client

RUN npm install

# Build the project
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build /home/client/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
