# Build stage
FROM node:14 AS build

WORKDIR /app

# Install dependencies
COPY client/package*.json ./
RUN npm install

# Copy the rest of your app's source code
COPY client/ .

# Build the project
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
