name: Build and Push Docker Image to ECR

on:
  push:
    branches: [feature/docker-workflow] # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Set the type of machine to run on

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2 # Use the official GitHub Actions action to check out the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # GitHub Action to set up Docker Buildx

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_DEFAULT_REGION: eu-west-1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
